# Generated by Django 2.2.6 on 2020-03-26 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='faculty_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_id', models.IntegerField()),
                ('faculty_name', models.CharField(blank=True, max_length=50, null=True)),
                ('faculty_email', models.CharField(blank=True, max_length=100, null=True)),
                ('faculty_image', models.ImageField(blank=True, null=True, upload_to='faculty_image/')),
                ('desc_faculty_edu', models.CharField(blank=True, max_length=100, null=True)),
                ('faculty_description_experience', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='institute_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.IntegerField(default=None)),
                ('institute_email', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('address2', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=150, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=50, null=True)),
                ('institute_mobile_no', models.CharField(blank=True, max_length=13, null=True)),
                ('institute_mobile_no2', models.CharField(blank=True, max_length=13, null=True)),
                ('institute_description', models.TextField(blank=True, max_length=300, null=True)),
                ('institute_logo', models.ImageField(blank=True, null=True, upload_to='institute_logo/')),
            ],
        ),
        migrations.CreateModel(
            name='rating_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_id', models.IntegerField()),
                ('average_rating', models.FloatField(default=0)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_detail.institute_information')),
            ],
        ),
        migrations.CreateModel(
            name='institute_result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_id', models.IntegerField()),
                ('institute_result', models.ImageField(default='http://dummyimage.com/60x60/666/ffffff&text=No+Image', upload_to='institute_result/')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_detail.institute_information')),
            ],
        ),
        migrations.CreateModel(
            name='Inst_review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('review', models.TextField(blank=True, max_length=300)),
                ('date', models.DateTimeField(auto_now=True, max_length=50, null=True)),
                ('review_star', models.IntegerField(default=None)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_detail.institute_information')),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_id', models.IntegerField()),
                ('institute_photos', models.ImageField(default='http://dummyimage.com/60x60/666/ffffff&text=No+Image', upload_to='institute_images/')),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_detail.institute_information')),
            ],
        ),
        migrations.CreateModel(
            name='course_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inst_id', models.IntegerField()),
                ('course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('course_catagery', models.CharField(blank=True, max_length=100, null=True)),
                ('cousrse_fees', models.CharField(max_length=50)),
                ('institute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='institute_detail.institute_information')),
            ],
        ),
    ]
