# Generated by Django 2.2.6 on 2020-03-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user_profile_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=None)),
                ('gender', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('mobile_no', models.IntegerField(default=None)),
                ('location', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Education', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('Profession', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('collage_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('interested_filed', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('user_bio', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('user_profile', models.ImageField(blank=True, null=True, upload_to='profile_images')),
            ],
        ),
    ]
