# Generated by Django 2.2.6 on 2020-03-26 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gate_privious_year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('course_catagery', models.CharField(blank=True, max_length=100, null=True)),
                ('Year_of_question_paper', models.CharField(blank=True, max_length=100, null=True)),
                ('question_paper', models.FileField(blank=True, null=True, upload_to='Gate_material/')),
                ('answer_key', models.FileField(blank=True, null=True, upload_to='Gate_material/')),
            ],
        ),
        migrations.CreateModel(
            name='online_mock_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=100, null=True)),
                ('course_catagery', models.CharField(blank=True, max_length=100, null=True)),
                ('mock_test_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
